In [2]:
import pandas as pd
dataframe_1 = pd.read_csv(filepath_or_buffer='sport_test.csv', index_col='학생번호')

In [3]:
dataframe_1

학년    악력  윗몸일으키기  점수  순위
학생번호                          
1      1  40.2      34  15   4
2      1  34.2      14   7  10
3      1  28.8      27  11   7
4      2  39.0      27  14   5
5      2  50.9      32  17   2
6      2  36.5      20   9   9
7      3  36.6      31  13   6
8      3  49.2      37  18   1
9      3  26.0      28  10   8
10     3  47.4      32  16   3

In [4]:
dataframe_1['악력']

학생번호
1     40.2
2     34.2
3     28.8
4     39.0
5     50.9
6     36.5
7     36.6
8     49.2
9     26.0
10    47.4
Name: 악력, dtype: float64

In [5]:
dataframe_1.describe()

학년         악력     윗몸일으키기         점수        순위
count  10.000000  10.000000  10.000000  10.000000  10.00000
mean    2.100000  38.880000  28.200000  13.000000   5.50000
std     0.875595   8.337306   6.828047   3.651484   3.02765
min     1.000000  26.000000  14.000000   7.000000   1.00000
25%     1.250000  34.775000  27.000000  10.250000   3.25000
50%     2.000000  37.800000  29.500000  13.500000   5.50000
75%     3.000000  45.600000  32.000000  15.750000   7.75000
max     3.000000  50.900000  37.000000  18.000000  10.00000

In [6]:
dataframe_1.shape

(10, 5)

In [9]:
dataframe_1.head()

학년    악력  윗몸일으키기  점수  순위
학생번호                          
1      1  40.2      34  15   4
2      1  34.2      14   7  10
3      1  28.8      27  11   7
4      2  39.0      27  14   5
5      2  50.9      32  17   2

In [11]:
dataframe_1.tail()

학년    악력  윗몸일으키기  점수  순위
학생번호                          
6      2  36.5      20   9   9
7      3  36.6      31  13   6
8      3  49.2      37  18   1
9      3  26.0      28  10   8
10     3  47.4      32  16   3

In [19]:
dataframe_1 = pd.read_csv(filepath_or_buffer='scores_em.csv', index_col='student number')
dataframe_1.head()

english  mathematics
student number                      
1                    42           65
2                    69           80
3                    56           63
4                    41           63
5                    57           76

In [20]:
scores = (dataframe_1['english'])[:10]

In [21]:
scores

student number
1     42
2     69
3     56
4     41
5     57
6     48
7     65
8     49
9     65
10    58
Name: english, dtype: int64

In [23]:
import numpy as np
scores = np.array(scores)
scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58], dtype=int64)

In [26]:
scores_dataframe_1 = pd.DataFrame(data={'score': scores},
index=pd.Index(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', ],
name='student'))
scores_dataframe_1

score
student       
A           42
B           69
C           56
D           41
E           57
F           48
G           65
H           49
I           65
J           58

In [27]:
english_scores = np.array(dataframe_1['english'])

In [28]:
english_scores

array([42, 69, 56, 41, 57, 48, 65, 49, 65, 58, 70, 47, 51, 64, 62, 70, 71,
       68, 73, 37, 65, 65, 61, 52, 57, 57, 75, 61, 47, 54, 66, 54, 54, 42,
       37, 79, 56, 62, 62, 55, 63, 57, 57, 67, 55, 45, 66, 55, 64, 66],
      dtype=int64)

In [29]:
english_scores.shape

(50,)

In [34]:
data_series2 = pd.Series(english_scores).describe()
data_series2

count    50.000000
mean     58.380000
std       9.799813
min      37.000000
25%      54.000000
50%      57.500000
75%      65.000000
max      79.000000
dtype: float64

In [37]:
z = (english_scores - np.mean(english_scores)) / np.std(english_scores)
z

array([-1.68843012,  1.09469645, -0.24532745, -1.79150888, -0.14224869,
       -1.06995755,  0.6823814 , -0.96687878,  0.6823814 , -0.03916993,
        1.19777521, -1.17303631, -0.76072126,  0.57930264,  0.37314512,
        1.19777521,  1.30085397,  0.99161769,  1.5070115 , -2.20382392,
        0.6823814 ,  0.6823814 ,  0.27006636, -0.6576425 , -0.14224869,
       -0.14224869,  1.71316902,  0.27006636, -1.17303631, -0.45148498,
        0.78546016, -0.45148498, -0.45148498, -1.68843012, -2.20382392,
        2.12548406, -0.24532745,  0.37314512,  0.37314512, -0.34840621,
        0.47622388, -0.14224869, -0.14224869,  0.88853893, -0.34840621,
       -1.37919383,  0.78546016, -0.34840621,  0.57930264,  0.78546016])